//! Batch loader for user programs
//! 
//! Loads user programs from embedded binaries

use super::task::TaskControlBlock;
use crate::task::TASK_MANAGER;
use core::arch::global_asm;

// Include the assembly file generated by build.rs
// This file contains the embedded user program binaries
// Reference: rCore uses global_asm! to include generated assembly
global_asm!(include_str!(concat!(env!("OUT_DIR"), "/link_apps.S")));

// External symbols from link_apps.S
extern "C" {
    fn _num_app();
    fn _app_0_start();
    fn _app_0_end();
    fn _app_1_start();
    fn _app_1_end();
    fn _app_2_start();
    fn _app_2_end();
    fn _app_3_start();
    fn _app_3_end();
    fn _app_4_start();
    fn _app_4_end();
}

/// Get number of apps
fn get_num_app() -> usize {
    unsafe {
        (_num_app as *const usize).read() as usize
    }
}

/// Get app data by index
fn get_app_data(app_id: usize) -> &'static [u8] {
    let app_start = match app_id {
        0 => _app_0_start as *const u8,
        1 => _app_1_start as *const u8,
        2 => _app_2_start as *const u8,
        3 => _app_3_start as *const u8,
        4 => _app_4_start as *const u8,
        _ => return &[],
    };
    
    let app_end = match app_id {
        0 => _app_0_end as *const u8,
        1 => _app_1_end as *const u8,
        2 => _app_2_end as *const u8,
        3 => _app_3_end as *const u8,
        4 => _app_4_end as *const u8,
        _ => return &[],
    };
    
    unsafe {
        core::slice::from_raw_parts(app_start, app_end as usize - app_start as usize)
    }
}

/// Load user programs in batch
pub fn load_apps() {
    crate::println!("[Loader] Loading user programs...");
    
    let num_app = get_num_app();
    crate::println!("[Loader] Found {} user programs", num_app);
    
    for i in 0..num_app {
        let app_data = get_app_data(i);
        if app_data.is_empty() {
            crate::println!("[Loader] Warning: App {} is empty, skipping", i);
            continue;
        }
        
        crate::println!("[Loader] Loading app {} (size: {} bytes)", i, app_data.len());
        
        let task = TaskControlBlock::new(app_data, i);
        let pid = TASK_MANAGER.lock().add_task(task);
        crate::println!("[Loader] Loaded app {} as task {}", i, pid);
    }
    
    crate::println!("[Loader] Loaded {} programs", TASK_MANAGER.lock().task_count());
}
